project_resource_branch: dev

tasks_resource_branch: dev

cf_resource_api: https://api.sys.vn01.pcf.dcsg.com
cf_resource_username: ((cf_user_nonprod))
cf_resource_password: ((cf_password_nonprod))
cf_resource_name: PCF-VN01-Dev
cf_resource_space: dev
cf_resource_push: cf-push-dev

aspnetcore_environment: Development